# Regression dengan KNN(K Nearest Neighbours)
- KNN adalah model machine learning yang dapat digunakan untuk melakukan prediksi berdasarkan karakteristik dengan sejumlah tetangga terdekat
-  Prediksi yang dapat dilakukan dapat diterapkan pada classification maupun regression task

In [44]:
# Sample Dataset
import pandas as pd
sensus = {'tinggi': [158,170,183,191,155,163,180,158,170],
          'berat': [64,86,84,80,49,59,67,54,67],
          'jk': ['pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita',]}
sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi  berat      jk
0     158     64    pria
1     170     86    pria
2     183     84    pria
3     191     80    pria
4     155     49  wanita
5     163     59  wanita
6     180     67  wanita
7     158     54  wanita
8     170     67  wanita

Regression dengan KNN

In [45]:
# Features & Target
import numpy as np
X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train:\n{X_train}\n')
print(f'y_train: {y_train}')

X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


Preprocess Dataset Konversi Label Menjadi Numerik Biner

In [46]:
X_train_transfosed = np.transpose(X_train)

print(f'X_train: \n{X_train}\n')
print(f'X_train_transposed:\n{X_train_transfosed}')

X_train: 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [47]:
from sklearn.preprocessing import LabelBinarizer 
lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transfosed[1])
print(f'jk:{X_train_transfosed[1]}\n')
print(f'jk_binarised:\n{jk_binarised}')


jk:['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised:
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [48]:
jk_binarised = jk_binarised.flatten() # untuk mengkonversi multidimensi array menjadi single dimensi
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [49]:
X_train_transfosed[1] = jk_binarised
X_train = X_train_transfosed.transpose()

print(f'X_train_transfosed:\n{X_train_transfosed}\n')
print(f'X-train:\n{X_train}')

X_train_transfosed:
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]

X-train:
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


In [50]:
from sklearn.neighbors import KNeighborsRegressor
K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

Prediksi Berat Badan

In [51]:
X_new = np.array([[155,1]])
X_new

array([[155,   1]])

In [52]:
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

Evaluasi KNN Regression Model

In [53]:
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

print(f'X_test:\n{X_test}\n')
print(f'y_test: {y_test}')


X_test:
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test: [65 96 52 67]


In [54]:
y_pred = model.predict(X_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

Coefficient of Determination

In [55]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test,y_pred)
print(f'R-squared: {r_squared}')
# nilai R-squared semakin mendekati nilai satu semakin baik dan berlaku sebaliknya

R-squared: 0.6290565226735438


Mean Absolute Error (MAE) atau Mean Absolute Deviation(MAD)
- MAE is the average of the absolute values of the errors of the prediction

In [56]:
from sklearn.metrics import mean_absolute_error
MAE = mean_absolute_error(y_test, y_pred)
print(f'MAE: {MAE}')
# Semakin kecil Nilai MAE maka mengindikasikan model semakin baik

MAE: 8.333333333333336


Mean Squared Erorr (MSE) atau Mean Squared Deviation(MAD)
- MAE is the average of the absolute values of the errors of the prediction

In [57]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(y_test, y_pred)
print(f'MSE: {MSE}')
# Semakin kecil nilai MSE maka akan mengindikasikan model yang baik

MSE: 95.8888888888889


Permasalahan Scaling pada nilai Features

In [58]:
from scipy.spatial.distance import euclidean

# tinggi dalam milimeter
X_train = np.array([[1700,0],[1600,1]])
X_new = np.array([[1640,0]])

[euclidean(X_new[0],d) for d in X_train]

[60.0, 40.01249804748511]

In [59]:
# Tinggi dalam meter
X_train = np.array([[1.7,0],[1.6,1]])
X_new = np.array([[1.64,0]])

[euclidean(X_new[0],d) for d in X_train]

[0.06000000000000005, 1.0007996802557444]

dapat dilihat pada kedua eksperimen bahwa eksperimen pertama memiliki jarak yang lebih dekat dengan eksperimen yang pertama,
untuk menghadapi permasalahn tersebut makan digunakan Standart Scaler(Scaler Score atau Z-Score)

Menerapkan Standart Scaler (Scaler Score atau Z-Score)
- Standarize features by removing the mean and scalling to unit variance

In [60]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [61]:
# tinggi dalam milimeter
X_train = np.array([[1700,0],[1600,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled:\n {X_train_scaled}\n')

X_new = np.array([[1640,0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled:\n {X_new_scaled}\n')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'jarak:{jarak}')




X_train_scaled:
 [[ 1. -1.]
 [-1.  1.]]

X_new_scaled:
 [[-0.2 -1. ]]

jarak:[1.2, 2.154065922853802]


In [62]:
# tinggi dalam meter
X_train = np.array([[1.7,0],[1.6,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train_scaled:\n {X_train_scaled}\n')

X_new = np.array([[1.64,0]])
X_new_scaled = ss.transform(X_new)
print(f'X_new_scaled:\n {X_new_scaled}\n')

jarak = [euclidean(X_new_scaled[0],d) for d in X_train_scaled]
print(f'jarak:{jarak}')
# nilai dalam satuan Z-score

X_train_scaled:
 [[ 1. -1.]
 [-1.  1.]]

X_new_scaled:
 [[-0.2 -1. ]]

jarak:[1.2000000000000026, 2.1540659228538006]


Menerapkan Features Scalling pada KNN

In [84]:
# Dataset
# Training Dataset
X_train = np.array([[158,0],[170,0],[183,0],[191,0,],[155,1],[163,1],[180,1],[158,1],[170,1]])
y_train = np.array([64,86,84,80,49,59,67,54,67])

# Test set
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

In [85]:
# Features Scalling (Standart Scaler)
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

print(f'X_train_scaled:\n{X_train_scaled}\n')
print(f'X_test_scaled:\n{X_test_scaled}\n')

X_train_scaled:
[[-0.9908706  -1.11803399]
 [ 0.01869567 -1.11803399]
 [ 1.11239246 -1.11803399]
 [ 1.78543664 -1.11803399]
 [-1.24326216  0.89442719]
 [-0.57021798  0.89442719]
 [ 0.86000089  0.89442719]
 [-0.9908706   0.89442719]
 [ 0.01869567  0.89442719]]

X_test_scaled:
[[-0.14956537 -1.11803399]
 [ 0.86000089 -1.11803399]
 [-0.82260955  0.89442719]
 [-0.06543485  0.89442719]]



In [86]:
# Training & Evaluasi Model
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)

print(f'MAE:{MAE}')
print(f'MSE:{MSE}')

MAE:7.583333333333336
MSE:85.13888888888893


dari perbandingan training dan evaluasi model dengan menggunakan features scalling hasil MAE dan MSE Lebih kecil atau dengan kata lain model yang dibuat dengan features scalling lebih baik